#!/bin/bash
#SBATCH --job-name=hbond
#SBATCH --output=mpi_%j.out
#SBATCH --error=mpi_%j.err
#SBATCH --ntasks=32
#SBATCH --time=00-2:00:00
#SBATCH --qos=debug

module purge
unset PYTHONPATH
module load ANACONDA/5.0.1
for i in /gpfs/projects/bsc72/vs/alm/ITK/crystals_analysis/Results/crossdocking/3V5J_neu; do python main.py "$i/rescoring/output/0/trajectory_*.pdb" -cpu 32 -o /gpfs/projects/bsc72/vs/alm/ITK/crystals_analysis/Hbond ; done
